In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\amans\Desktop\DVA\experiment 2\insurance.csv")

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [3]:
df.shape

(1338, 7)

In [4]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [8]:
# Calculate mean of age
mean_age = df["age"].mean()

print("Mean of Age:", mean_age)

Mean of Age: 39.20702541106129

In [5]:
df.mean(numeric_only=True)

age            39.207025
bmi            30.663397
children        1.094918
charges     13270.422265
dtype: float64

In [6]:
df.median(numeric_only=True)

age           39.000
bmi           30.400
children       1.000
charges     9382.033
dtype: float64

In [7]:
df.mode()

   age   sex   bmi  children smoker     region    charges
0   18  male  32.3         0     no  southeast  1639.5631

In [11]:
# Calculate variance of age
variance_age = df["age"].var()

print("Variance of Age:", variance_age)

Variance of Age: 197.40138665754424

In [12]:
# Calculate standard deviation of age
std_age = df["age"].std()

print("Standard Deviation of Age:", std_age)

Standard Deviation of Age: 14.049960379216172

In [9]:
df.var(numeric_only=True)

age         1.974014e+02
bmi         3.718788e+01
children    1.453213e+00
charges     1.466524e+08
dtype: float64

In [10]:
df.std(numeric_only=True)

age            14.049960
bmi             6.098187
children        1.205493
charges     12110.011237
dtype: float64

In [14]:
quartiles = df["charges"].quantile([0.25, 0.50, 0.75])

print(quartiles)

0.25     4740.287150
0.50     9382.033000
0.75    16639.912515
Name: charges, dtype: float64

In [13]:
df.quantile([0.25,0.50,0.75], numeric_only=True)

       age       bmi  children       charges
0.25  27.0  26.29625       0.0   4740.287150
0.50  39.0  30.40000       1.0   9382.033000
0.75  51.0  34.69375       2.0  16639.912515

In [18]:
# Correlation matrix for age and bmi
df[["age", "bmi"]].corr()

          age       bmi
age  1.000000  0.109272
bmi  0.109272  1.000000

In [17]:
df.corr()

               age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

In [19]:
# ==========================================
# Using NumPy for Descriptive Statistics
# Calculate Mean, Median, Standard Deviation,
# and Variance of the 'charges' column
# ==========================================

import numpy as np

# Mean
print("Mean of Charges:", np.mean(df["charges"]))

# Median
print("Median of Charges:", np.median(df["charges"]))

# Standard Deviation
print("Standard Deviation of Charges:", np.std(df["charges"], ddof=1))

# Variance
print("Variance of Charges:", np.var(df["charges"], ddof=1))

Mean of Charges: 13270.422265141257
Median of Charges: 9382.033
Standard Deviation of Charges: 12110.011236693994
Variance of Charges: 146652372.1528548

In [21]:
# ==========================================
# Using SciPy for Descriptive Statistics
# Calculate Mode of the 'children' column
# ==========================================

from scipy import stats

# Calculate Mode
mode_result = stats.mode(df["children"])

print("Mode of Children:", mode_result.mode[0])
print("Frequency:", mode_result.count[0])

Mode of Children: 0
Frequency: 574

In [22]:
# Display all statistical measures together
print("Mean:\n", df.mean(numeric_only=True))
print("\nMedian:\n", df.median(numeric_only=True))
print("\nMode:\n", df.mode().iloc[0])
print("\nVariance:\n", df.var(numeric_only=True))
print("\nStandard Deviation:\n", df.std(numeric_only=True))
print("\nQuartiles:\n", df.quantile([0.25,0.5,0.75], numeric_only=True))
print("\nCorrelation:\n", df.corr(numeric_only=True))

Mean:
 age            39.207025
bmi            30.663397
children        1.094918
charges     13270.422265
dtype: float64

Median:
 age           39.000
bmi           30.400
children       1.000
charges     9382.033
dtype: float64

Mode:
 age                18
sex              male
bmi              32.3
children            0
smoker             no
region      southeast
charges       1639.56
Name: 0, dtype: object

Variance:
 age         1.974014e+02
bmi         3.718788e+01
children    1.453213e+00
charges     1.466524e+08
dtype: float64

Standard Deviation:
 age            14.049960
bmi             6.098187
children        1.205493
charges     12110.011237
dtype: float64

Quartiles:
        age       bmi  children       charges
0.25  27.0  26.29625       0.0   4740.287150
0.50  39.0  30.40000       1.0   9382.033000
0.75  51.0  34.69375       2.0  16639.912515

TypeError: corr() got an unexpected keyword argument 'numeric_only'